export const GET_EC2_SERVERS_REQUEST = "@app/aws/GET_EC2_SERVERS_REQUEST";
export const GET_EC2_SERVERS_SUCCESS = "@app/aws/GET_EC2_SERVERS_SUCCESS";
export const GET_EC2_SERVERS_FAILURE = "@app/aws/GET_EC2_SERVERS_FAILURE";
export const CREATE_EC2_SUCCESS = "@app/aws/CREATE_EC2_SUCCESS";
export const DELETE_EC2_SUCCESS = "@app/aws/DELETE_EC2_SUCCESS";
export const SELECT_DELETE_EC2 = "@app/aws/SELECT_DELETE_EC2";
export const COMMON_REQUEST = "@app/aws/COMMON_REQUEST";
export const COMMON_FAILURE = "@app/aws/COMMON_FAILURE";
export const COMMON_SUCCESS = "@app/aws/COMMON_SUCCESS";
export const GET_PEM_FILES_REQUEST = "@app/aws/GET_PEM_FILES_REQUEST";
export const GET_PEM_FILES_FAILURE = "@app/aws/GET_PEM_FILES_FAILURE";
export const GET_PEM_FILES_SUCCESS = "@app/aws/GET_PEM_FILES_SUCCESS";
export const CREATE_PEM_FILE_SUCCESS_AND_FAIL =
  "@app/aws/CREATE_PEM_FILE_SUCCESS_AND_FAIL";
export const CREATE_PEM_FILE_REQUEST = "@app/aws/CREATE_PEM_FILE_REQUEST";
export const TOGGLE_CREATE_EC2_FORM = "@app/aws/TOGGLE_CREATE_EC2_FORM";
