# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19.1'
      - name: Install dependencies
        run: |
          sudo apt-get install build-essential wget zip  libc6-dev-arm64-cross && \
          echo "/usr/bin/x86_64-w64-mingw32-gcc" >> GITHUB_PATH && \
          wget --no-check-certificate --progress=dot:mega https://github.com/wangyoucao577/assets-uploader/releases/download/v0.3.0/github-assets-uploader-v0.3.0-linux-amd64.tar.gz -O github-assets-uploader.tar.gz && \
          tar -zxf github-assets-uploader.tar.gz && \
          sudo mv github-assets-uploader /usr/sbin/ && \
          sudo rm -f github-assets-uploader.tar.gz && \
          github-assets-uploader -version
      - name: Install gox
        run: go install github.com/mitchellh/gox@latest
      - name: Set VERSION env
        run: echo VERSION=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}
      - name: Build package
        run: |
          make clean && \
          make build && \
          mv server/.env.example build/.env
          pwd && \
          mkdir loadster-${VERSION}-darwin-amd64 && cp -rf build/darwin/amd64/server build/.env strain-ui/dist loadster-${VERSION}-darwin-amd64/ && tar cvfz loadster-${VERSION}-darwin-amd64.tar.gz loadster-${VERSION}-darwin-amd64 && \
          mkdir loadster-${VERSION}-linux-amd64 && cp -rf build/linux/amd64/server build/.env strain-ui/dist loadster-${VERSION}-linux-amd64/ && tar cvfz loadster-${VERSION}-linux-amd64.tar.gz loadster-${VERSION}-linux-amd64 && \
          mkdir loadster-${VERSION}-linux-arm64 && cp -rf build/linux/arm64/server build/.env strain-ui/dist loadster-${VERSION}-linux-arm64/ && tar cvfz loadster-${VERSION}-linux-arm64.tar.gz loadster-${VERSION}-linux-arm64 && \
          mkdir loadster-${VERSION}-windows-amd64 && cp -rf build/windows/amd64/server.exe build/.env strain-ui/dist loadster-${VERSION}-windows-amd64/ && tar cvfz loadster-${VERSION}-windows-amd64.tar.gz loadster-${VERSION}-windows-amd64 && \
          ls
      # - name: Upload assets
      #   run: |
      #     github-assets-uploader -f loadster-${VERSION}-darwin.tar.gz -mediatype application/gzip -repo cirnum/strain-hub -token ${{secrets.GITHUB_TOKEN}} -tag ${VERSION}

      # step 3: Copy build-artifacts in the GitHub release
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./*.tar.gz"
